name: my-setup-go
description: 'Common setup-go steps for this project'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version-file: ./go.mod
        cache: true
    - name: Generate code
      run: make gogen
      shell: bash
