name: my-setup-go
description: 'Common setup-go steps for this project'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Generate code
      run: make gogen
      shell: bash
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
