name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  GO_VERSION: 1.18
  MYSQL_PASS: password
  MYSQL_NAME: myapp

jobs:
  test-unit:
    name: Test (Unit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Generate code
        run: make gogen
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Check tests
        run: make test-unit

  test-integration:
    name: Test (Integration)
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASS }}
          MYSQL_DATABASE: ${{ env.MYSQL_NAME }}
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Generate code
        run: make gogen
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Check tests
        run: make test-integration

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Generate code
        run: make gogen
      - uses: reviewdog/action-golangci-lint@v2
