name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-unit:
    name: Test (Unit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/my-setup-go
      - name: Check tests
        run: make test-unit

  test-integration:
    name: Test (Integration)
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/my-setup-go
      - name: Check tests
        run: make test-integration

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/my-setup-go
      - uses: reviewdog/action-golangci-lint@v2
