name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  GO_VERSION: 1.18
  CGO_ENABLED: 0

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -race -v ./...

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test (Unit)
        run: make test-unit

      - name: Test (Integration)
        run: make test-integration

      - name: Lint
        uses: reviewdog/action-golangci-lint@v2
